services:
  carbote-bot:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./app:/app
    environment:
      _BOT_TOKEN_: ${_BOT_TOKEN_}
      _AIRTABLE_TOKEN_: ${_AIRTABLE_TOKEN_}